# Generated by Django 5.1.6 on 2025-03-03 04:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.TimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержание')),
                ('category_choice', models.CharField(choices=[('Tk', 'Tanks'), ('Hl', 'Heal'), ('DD', 'DD'), ('Dl', 'Dealer'), ('Gm', 'Gildmasteers'), ('Qg', 'Questgivers'), ('Bs', 'Вlacksmith'), ('Sk', 'Skinner'), ('Ach', 'Alchemist'), ('Wof', 'Wizard of spells')], default='Tk', max_length=3, verbose_name='Category choice')),
                ('media', tinymce.models.HTMLField(verbose_name='Медиа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('users', models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Description')),
                ('timecreated', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('acception_choice', models.CharField(choices=[('accept', 'Accept'), ('reject', 'reject')], default='reject', max_length=7, verbose_name='Accept/Reject')),
                ('post_replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='Post replied')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Replies', to=settings.AUTH_USER_MODEL, verbose_name='User replied')),
            ],
        ),
    ]
