# Generated by Django 5.1.6 on 2025-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, max_length=1000000),
        ),
    ]
