# Generated by Django 5.1.6 on 2025-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Media'),
        ),
    ]
